# Generated by Django 2.2 on 2020-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attendee',
        ),
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(related_name='trips', to='tripsapp.User'),
        ),
    ]
